Fixes due to API change of Cadence client

diff --git a/vendor/go.uber.org/cadence/Makefile b/vendor/go.uber.org/cadence/Makefile
--- a/vendor/go.uber.org/cadence/Makefile
+++ b/vendor/go.uber.org/cadence/Makefile
@@ -10,29 +10,26 @@ default: test
 
 # define the list of thrift files the service depends on
 # (if you have some)
-THRIFT_SRCS = idl/github.com/uber/cadence/cadence.thrift \
-	idl/github.com/uber/cadence/shared.thrift \
+THRIFTRW_SRCS = \
+  idl/github.com/uber/cadence/cadence.thrift \
+  idl/github.com/uber/cadence/shared.thrift \
 
 PROGS = cadence-client
 TEST_ARG ?= -race -v -timeout 5m
 BUILD := ./build
 
-export PATH := $(GOPATH)/bin:$(PATH)
-
 THRIFT_GEN=$(GOPATH)/bin/thrift-gen
 
+define thriftrwrule
+THRIFTRW_GEN_SRC += $(THRIFT_GENDIR)/go/$1/$1.go
 
-define thriftrule
-THRIFT_GEN_SRC += $(THRIFT_GENDIR)/go/$1/tchan-$1.go
-
-$(THRIFT_GENDIR)/go/$1/tchan-$1.go:: $2 $(THRIFT_GEN)
+$(THRIFT_GENDIR)/go/$1/$1.go:: $2
 	@mkdir -p $(THRIFT_GENDIR)/go
-	$(ECHO_V)$(THRIFT_GEN) --generateThrift --packagePrefix $(PROJECT_ROOT)/$(THRIFT_GENDIR)/go/ --inputFile $2 --outputDir $(THRIFT_GENDIR)/go \
-		$(foreach template,$(THRIFT_TEMPLATES), --template $(template))
+	$(ECHO_V)thriftrw --plugin=yarpc --pkg-prefix=$(PROJECT_ROOT)/$(THRIFT_GENDIR)/go/ --out=$(THRIFT_GENDIR)/go $2
 endef
 
-$(foreach tsrc,$(THRIFT_SRCS),$(eval $(call \
-	thriftrule,$(basename $(notdir \
+$(foreach tsrc,$(THRIFTRW_SRCS),$(eval $(call \
+	thriftrwrule,$(basename $(notdir \
 	$(shell echo $(tsrc) | tr A-Z a-z))),$(tsrc))))
 
 # Automatically gather all srcs
@@ -47,20 +44,24 @@ LINT_SRC := $(filter-out ./mock%,$(ALL_SRC))
 # all directories with *_test.go files in them
 TEST_DIRS := $(sort $(dir $(filter %_test.go,$(ALL_SRC))))
 
-glide:
-	glide install
+yarpc-install:
+	go get './vendor/go.uber.org/thriftrw'
+	go get './vendor/go.uber.org/yarpc/encoding/thrift/thriftrw-plugin-yarpc'
 
 clean_thrift:
 	rm -rf .gen
 
-thriftc: clean_thrift $(THRIFT_GEN_SRC)
+thriftc: clean_thrift yarpc-install $(THRIFTRW_GEN_SRC)
 
-copyright: ./cmd/tools/copyright/licensegen.go
-	go run ./cmd/tools/copyright/licensegen.go --verifyOnly
+copyright: ./internal/cmd/tools/copyright/licensegen.go
+	go run ./internal/cmd/tools/copyright/licensegen.go --verifyOnly
 
-bins_nothrift: copyright lint glide
+vendor/glide.updated: glide.lock glide.yaml
+	glide install
+	touch vendor/glide.updated
 
-bins: thriftc bins_nothrift
+dummy: vendor/glide.updated $(ALL_SRC)
+	go build -i -o dummy internal/cmd/dummy/dummy.go
 
 test: bins
 	@rm -f test
@@ -69,22 +70,24 @@ test: bins
 		go test -race -coverprofile=$@ "$$dir" | tee -a test.log; \
 	done;
 
-cover_profile: clean bins_nothrift
+bins: thriftc copyright lint dummy
+
+cover_profile: clean copyright lint vendor/glide.updated
+	@mkdir -p $(BUILD)
+	@echo "mode: atomic" > $(BUILD)/cover.out
+
 	@echo Testing packages:
 	@for dir in $(TEST_DIRS); do \
 		mkdir -p $(BUILD)/"$$dir"; \
 		go test "$$dir" $(TEST_ARG) -coverprofile=$(BUILD)/"$$dir"/coverage.out || exit 1; \
+		cat $(BUILD)/"$$dir"/coverage.out | grep -v "mode: atomic" >> $(BUILD)/cover.out; \
 	done;
 
 cover: cover_profile
-	@for dir in $(TEST_DIRS); do \
-		go tool cover -html=$(BUILD)/"$$dir"/coverage.out; \
-	done
+	go tool cover -html=$(BUILD)/cover.out;
 
 cover_ci: cover_profile
-	@for dir in $(TEST_DIRS); do \
-		goveralls -coverprofile=$(BUILD)/"$$dir"/coverage.out -service=travis-ci || echo -e "\x1b[31mCoveralls failed\x1b[m"; \
-	done
+	goveralls -coverprofile=$(BUILD)/cover.out -service=travis-ci || echo -e "\x1b[31mCoveralls failed\x1b[m";
 
 
 lint:
@@ -103,6 +106,7 @@ lint:
 fmt:
 	@gofmt -w $(ALL_SRC)
 
-
 clean:
 	rm -rf cadence-client
+	rm -Rf $(BUILD)
+	rm -f dummy
